/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.stem.lifeinmotion;

/**
 *
 * @author nit
 */
public class LifeInMotion extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public LifeInMotion() {
        initComponents();
        
        this.setTitle("Life In Motion");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        ageField = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        stepsLabel = new javax.swing.JLabel();
        stepsField = new javax.swing.JTextField();
        standingLabel = new javax.swing.JLabel();
        standingField = new javax.swing.JTextField();
        smartScoreLabel = new javax.swing.JLabel();
        discountLabel = new javax.swing.JLabel();
        calculateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setName("Life In Motion"); // NOI18N

        Panel.setBackground(new java.awt.Color(0, 0, 0));
        Panel.setName("Life In Motion"); // NOI18N

        titleLabel.setBackground(new java.awt.Color(0, 0, 0));
        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 0, 0));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Life In Motion Demo");

        ageField.setBackground(java.awt.SystemColor.desktop);
        ageField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ageField.setForeground(new java.awt.Color(255, 0, 0));
        ageField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ageField.setText("Client's Age");
        ageField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ageFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ageFieldFocusLost(evt);
            }
        });

        ageLabel.setBackground(new java.awt.Color(0, 0, 0));
        ageLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(255, 0, 0));
        ageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ageLabel.setText("Age:");

        stepsLabel.setBackground(new java.awt.Color(0, 0, 0));
        stepsLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        stepsLabel.setForeground(new java.awt.Color(255, 0, 0));
        stepsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stepsLabel.setText("Steps:");

        stepsField.setBackground(java.awt.SystemColor.desktop);
        stepsField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        stepsField.setForeground(new java.awt.Color(255, 0, 0));
        stepsField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        stepsField.setText("Client's Steps");
        stepsField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stepsFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stepsFieldFocusLost(evt);
            }
        });

        standingLabel.setBackground(new java.awt.Color(0, 0, 0));
        standingLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        standingLabel.setForeground(new java.awt.Color(255, 0, 0));
        standingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        standingLabel.setText("Time Standing:");

        standingField.setBackground(java.awt.SystemColor.desktop);
        standingField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        standingField.setForeground(new java.awt.Color(255, 0, 0));
        standingField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        standingField.setText("Client's Standing Minutes");
        standingField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                standingFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                standingFieldFocusLost(evt);
            }
        });

        smartScoreLabel.setBackground(new java.awt.Color(0, 0, 0));
        smartScoreLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        smartScoreLabel.setForeground(new java.awt.Color(255, 0, 0));
        smartScoreLabel.setText("Smart Score: N/A");

        discountLabel.setBackground(new java.awt.Color(0, 0, 0));
        discountLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        discountLabel.setForeground(new java.awt.Color(255, 0, 0));
        discountLabel.setText("Discount: N/A");

        calculateButton.setBackground(java.awt.SystemColor.desktop);
        calculateButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        calculateButton.setForeground(new java.awt.Color(255, 0, 0));
        calculateButton.setText("Calculate");
        calculateButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        calculateButton.setContentAreaFilled(false);
        calculateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        calculateButton.setFocusPainted(false);
        calculateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                calculateButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(smartScoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(stepsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                            .addComponent(standingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(standingField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stepsField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(discountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stepsLabel)
                    .addComponent(stepsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(standingLabel)
                    .addComponent(standingField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106)
                .addComponent(smartScoreLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(discountLabel)
                .addGap(74, 74, 74)
                .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ageFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFieldFocusGained
        if (ageField.getText().equals("Client's Age")) {
            ageField.setText("");
        }
    }//GEN-LAST:event_ageFieldFocusGained

    private void ageFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFieldFocusLost
        if (ageField.getText().isBlank()) {
            ageField.setText("Client's Age");
        }
    }//GEN-LAST:event_ageFieldFocusLost

    private void stepsFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stepsFieldFocusGained
        if (stepsField.getText().equals("Client's Steps")) {
            stepsField.setText("");
        }
    }//GEN-LAST:event_stepsFieldFocusGained

    private void stepsFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stepsFieldFocusLost
        if (stepsField.getText().isBlank()) {
            stepsField.setText("Client's Steps");
        }
    }//GEN-LAST:event_stepsFieldFocusLost

    private void standingFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_standingFieldFocusGained
        if (standingField.getText().equals("Client's Standing Minutes")) {
            standingField.setText("");
        }
    }//GEN-LAST:event_standingFieldFocusGained

    private void standingFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_standingFieldFocusLost
        if (standingField.getText().isBlank()) {
            standingField.setText("Client's Standing Minutes");
        }
    }//GEN-LAST:event_standingFieldFocusLost

    private void calculateButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculateButtonMousePressed
        try {
            int steps = Integer.parseInt(stepsField.getText());
            int standingMinutes = Integer.parseInt(standingField.getText());
            int age = Integer.parseInt(ageField.getText());

            if (steps < 0 || standingMinutes < 0 || age < 0) {
                javax.swing.JOptionPane.showMessageDialog(Panel, "Please enter valid numbers!", "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }

            int smartScore = 0;
            int stepScore = 0;
            int standScore = 0;
            int discount = 0;

            if (steps <= 5_000) {
                stepScore = 0;
            } else if (steps <= 7_000) {
                stepScore = 1;
            } else if (steps <= 10_000) {
                stepScore = 2;
            } else if (steps <= 15_000) {
                stepScore = 3;
            } else if (steps <= 20_000) {
                stepScore = 4;
            } else if (steps >= 20_000) {
                stepScore = 5;
            }

            if (standingMinutes <= 30) {
                standScore = 0;
            } else if (standingMinutes <= 60) {
                standScore = 1;
            } else if (standingMinutes <= 90) {
                standScore = 2;
            } else if (standingMinutes <= 120) {
                standScore = 3;
            } else if (standingMinutes <= 150) {
                standScore = 4;
            } else if (standingMinutes >= 180) {
                standScore = 5;
            }

            smartScore = (int)((stepScore * 1.2) + standScore) / 2;
            discount = (int)((smartScore * 5) * ((double)age / 100));

            smartScoreLabel.setText("Smart Score: " + smartScore);
            discountLabel.setText("Discount: " + discount + '%');
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(Panel, "Please enter valid numbers!", "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_calculateButtonMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LifeInMotion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LifeInMotion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LifeInMotion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LifeInMotion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LifeInMotion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JButton calculateButton;
    private javax.swing.JLabel discountLabel;
    private javax.swing.JLabel smartScoreLabel;
    private javax.swing.JTextField standingField;
    private javax.swing.JLabel standingLabel;
    private javax.swing.JTextField stepsField;
    private javax.swing.JLabel stepsLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
